### ISSUE TITLE
Verify for only allowed fields

### ISSUE THREAD

**Issue by itpropro** [kevinmarrec/h3-typebox#3]
Hey @kevinmarrec,
great h3 addition, I had no problems with using it so far. As I am pretty new to TypeBox, I wanted to ask, what the best way would be to make sure that only the provided fields are actually on the request?
From a security perspective, it is discussable, but sometimes you want to have `paramA`, `paramB` and `paramC` as query parameter and used validateQuery to define them as string (what query strings always are). If a user now queries the url with `paramX`, it will not throw an error, as the field will not be verified by typebox. 
Is there any way to handle a catch all for all parameters/body entries that are not part of the schema or is this something you would implement in nitro natively?

**Comment by itpropro** [comment]
I think the correct way with typebox would be this:

```typescript
  const query = validateQuery(event, Type.Object({
    paramA: Type.Optional(Type.String()),
    paramB: Type.Optional(Type.String()),
    paramC: Type.Optional(Type.String()),
  }, { additionalProperties: false }))
```

**Comment by kevinmarrec** [comment]
I don't have more knowledge in Typebox to be honest, but looks like you found your way to go !
