### ISSUE TITLE
Code generation from strings disallowed for this context

### ISSUE THREAD

**Issue by cosbgn** [kevinmarrec/h3-typebox#8]
When running `validateBody` (probably also the other helpers), it throws an error in production on vercel-edge (cloudflare workers). Most likely because they restrict certain JavaScript functions like eval(), new Function(), setTimeout([string]), and setInterval([string]), which can execute code generated from strings.

I'm not sure why these functions are needed but it would be better to avoid them.

**Comment by itpropro** [comment]
Can you please provide a reproduction repo or create a PR that fixes that? I couldn't find any these methods in the code base, but validateBody is just a wrapper around `ajv`, so the core problem is probably in their implementation.

**Comment by cosbgn** [comment]
Yes, after further inspection I found that the problem is actually from
ajv, so we can close this.
